import * as React from 'react';
import { StyleSheet, View } from 'react-native';
import CustomFlatlist from '../components/CustomFlatlist';
import CustomHeader from '../components/CustomHeader';

const agents = [
  {
    id: 1,
    name: 'Brimstone',
    country: 'Estados Unidos',
    biography:
      'Vindo diretamente dos EUA, o arsenal orbital de Brimstone garante que o esquadrão dele esteja sempre em vantagem. Sua capacidade de oferecer utilidade com precisão a distância faz dele um comandante inigualável na linha de frente.',
    basicHabilities: ['Incendiário', 'Fumaça Celeste'],
    signatureHability: ['Sinalizador Estimulante'],
    ultimateHability: ['Ataque Orbital'],
    aliases: ['Brim'],
    race: 'Humano',
    role: 'Controlador',
    codename: 'Sarge',
    gunSkin: 'Peacekeeper Sheriff',
    icon: require('../assets/images/icons/Brimstone.png'),
    horizontalCard1: require('../assets/images/horizontalCards/Brimstone.jpg'),
    horizontalCard2: require('../assets/images/horizontalCards/Brimstone2.jpg'),
  },
  {
    id: 2,
    name: 'Viper',
    country: 'Estados Unidos',
    biography:
      'Viper, a química dos Estados Unidos, emprega uma variedade de dispositivos químicos venenosos para controlar o campo de batalha e prejudicar a visão do inimigo. Se as toxinas não matarem a presa, seus jogos mentais certamente o farão.',
    basicHabilities: ['Veneno de Cobra', 'Nuvem Venenosa'],
    signatureHability: ['Cortina Tóxica'],
    ultimateHability: ['Poço Peçonhento'],
    aliases: ['Sabine'],
    race: 'Humano',
    role: 'Controlador',
    codename: 'Pandemic',
    gunSkin: 'Snakebite Shorty',
    icon: require('../assets/images/icons/Viper.png'),
    horizontalCard1: require('../assets/images/horizontalCards/Viper.jpg'),
    horizontalCard2: require('../assets/images/horizontalCards/Viper2.jpg'),
  },
  {
    id: 3,
    name: 'Omen',
    country: 'Desconhecido',
    biography:
      'Omen, uma lembrança fantasmagórica, caça nas sombras. Ele cega os inimigos, teleporta-se pelo campo e deixa a paranoia assumir o controle enquanto o adversário tenta descobrir de onde virá seu próximo ataque.',
    basicHabilities: ['Passos Tenebrosos', 'Paranoia'],
    signatureHability: ['Manto Sombrio'],
    ultimateHability: ['Salto das Sombras'],
    aliases: ['Ja-'],
    race: 'Radiante',
    role: 'Controlador',
    codename: 'Wraith',
    gunSkin: 'Soul Silencer Ghost',
    icon: require('../assets/images/icons/Omen.png'),
    horizontalCard1: require('../assets/images/horizontalCards/Omen.jpg'),
    horizontalCard2: require('../assets/images/horizontalCards/Omen2.jpg'),
  },
  {
    id: 4,
    name: 'Killjoy',
    country: 'Alemanha',
    biography:
      'Killjoy, uma alemã genial, defende o campo de batalha facilmente usando seu arsenal de invenções. Se o dano causado por seu equipamento não der cabo dos inimigos, os efeitos negativos de seus queridos robôs dão conta do recado.',
    basicHabilities: ['Nanoenxame', 'Robô de Alarme'],
    signatureHability: ['Torreta'],
    ultimateHability: ['Confinamento'],
    aliases: [],
    race: 'Humano',
    role: 'Sentinela',
    codename: '',
    gunSkin: 'Wunderkind Shorty',
    icon: require('../assets/images/icons/Killjoy.png'),
    horizontalCard1: require('../assets/images/horizontalCards/Killjoy.jpg'),
    horizontalCard2: require('../assets/images/horizontalCards/Killjoy2.jpg'),
  },
  {
    id: 5,
    name: 'Cypher',
    country: 'Marrocos',
    biography:
      'Cypher, um vendedor de informações do Marrocos, é uma verdadeira rede de vigilância de um homem só que fica de olho em cada movimento dos inimigos. Nenhum segredo está a salvo. Nenhuma manobra passa despercebida. Cypher está sempre vigiando.',
    basicHabilities: ['Jaula Cibernética', 'Fio-armadilha'],
    signatureHability: ['Câmera de Vigilância'],
    ultimateHability: ['Assalto Neural'],
    aliases: ['Aamir'],
    race: 'Humano',
    role: 'Sentinela',
    codename: 'Gumshoe',
    gunSkin: 'Hush Ghost',
    icon: require('../assets/images/icons/Cypher.png'),
    horizontalCard1: require('../assets/images/horizontalCards/Cypher.jpg'),
    horizontalCard2: require('../assets/images/horizontalCards/Cypher2.jpg'),
  },
  {
    id: 6,
    name: 'Sova',
    country: 'Rússia',
    biography:
      'Nascido sob o eterno inverno das tundras russas, Sova rastreia, encontra e elimina inimigos com eficiência e precisão implacáveis. Seu arco personalizado e suas habilidades inigualáveis de reconhecimento garantem que nenhuma presa escape.',
    basicHabilities: ['Flecha de Choque', 'Drone Coruja'],
    signatureHability: ['Flecha Rastreadora'],
    ultimateHability: ['Fúria do Caçador'],
    aliases: [],
    race: 'Humano',
    role: 'Iniciador',
    codename: 'Hunter',
    gunSkin: 'Protektor Sheriff',
    icon: require('../assets/images/icons/Sova.png'),
    horizontalCard1: require('../assets/images/horizontalCards/Sova.jpg'),
    horizontalCard2: require('../assets/images/horizontalCards/Sova2.jpg'),
  },
  {
    id: 7,
    name: 'Sage',
    country: 'China',
    biography:
      'Como uma verdadeira fortaleza chinesa, Sage traz segurança para si mesma e para a equipe aonde quer que vá. Capaz de reviver aliados e rechaçar investidas agressivas, ela oferece um centro de calmaria em meio ao caos da batalha.',
    basicHabilities: ['Orbe de Lentidão', 'Orbe de Barreira'],
    signatureHability: ['Orbe Curativo'],
    ultimateHability: ['Ressureição'],
    aliases: [],
    race: 'Radiante',
    role: 'Sentinela',
    codename: 'Thorne',
    gunSkin: 'Final Chamber Classic',
    icon: require('../assets/images/icons/Sage.png'),
    horizontalCard1: require('../assets/images/horizontalCards/Sage.jpg'),
    horizontalCard2: require('../assets/images/horizontalCards/Sage2.jpg'),
  },
  {
    id: 9,
    name: 'Phoenix',
    country: 'Reino Unido',
    biography:
      'Chegando com tudo diretamente do Reino Unido, o poder estelar de Phoenix reluz em seu estilo de luta, incendiando o campo de batalha com luz e estilo. Tendo ajuda ou não, ele entra na luta como e quando achar que deve.',
    basicHabilities: ['Bola Curva', 'Labareda'],
    signatureHability: ['Mãos Quentes'],
    ultimateHability: ['Renascimento'],
    aliases: [],
    race: 'Radiante',
    role: 'Duelista',
    codename: 'Apollo',
    gunSkin: 'Spitfire Frenzy',
    icon: require('../assets/images/icons/Phoenix.png'),
    horizontalCard1: require('../assets/images/horizontalCards/Phoenix.jpg'),
    horizontalCard2: require('../assets/images/horizontalCards/Phoenix2.jpg'),
  },
  {
    id: 10,
    name: 'Jett',
    country: 'Coréia do Sul',
    biography:
      'Representando a Coreia do Sul, sua terra natal, Jett tem um estilo de luta ágil e evasivo que permite que ela assuma riscos como ninguém. Ela corre em meio a qualquer confronto, cortando os inimigos antes mesmo que eles percebam quem ou o que os atingiu.',
    basicHabilities: ['Corrente Ascendente', 'Erupção das Brumas'],
    signatureHability: ['Brisa de Impulso'],
    ultimateHability: ['Tormenta de Aço'],
    aliases: ['Joon-Hee'],
    race: 'Radiante',
    role: 'Duelista',
    codename: 'Hawk',
    gunSkin: 'Game Over Sheriff',
    icon: require('../assets/images/icons/Jett.png'),
    horizontalCard1: require('../assets/images/horizontalCards/Jett.jpg'),
    horizontalCard2: require('../assets/images/horizontalCards/Jett2.jpg'),
  },
  {
    id: 11,
    name: 'Reyna',
    country: 'México',
    biography:
      'Criada no coração do México, Reyna domina o combate individual, destacando-se a cada abate efetuado. Sua capacidade só é limitada por sua própria perícia, tornando-a bastante dependente de desempenho.',
    basicHabilities: ['Devorar', 'Olhar Veroz'],
    signatureHability: ['Dispensar'],
    ultimateHability: ['Imperatriz'],
    aliases: [],
    race: 'Radiante',
    role: 'Duelista',
    codename: 'Vampire',
    gunSkin: 'Vendetta Ghost',
    icon: require('../assets/images/icons/Reyna.png'),
    horizontalCard1: require('../assets/images/horizontalCards/Reyna.jpg'),
    horizontalCard2: require('../assets/images/horizontalCards/Reyna2.jpg'),
  },
  {
    id: 12,
    name: 'Raze',
    country: 'Brasil',
    biography:
      'Raze chega do Brasil em uma explosão de carisma e armas letais. Com seu estilo de jogo "porradeiro", ela é craque em desentocar inimigos entrincheirados e limpar espaços apertados com uma bela dose de BUUUM!',
    basicHabilities: ['Carga de Explosivos', 'Bumba'],
    signatureHability: ['Cartuchos de Tinta'],
    ultimateHability: ['Estraga-Prazeres'],
    aliases: [],
    race: 'Humano',
    role: 'Duelista',
    codename: 'Clay',
    gunSkin: 'Pistolinha Classic',
    icon: require('../assets/images/icons/Raze.png'),
    horizontalCard1: require('../assets/images/horizontalCards/Raze.jpg'),
    horizontalCard2: require('../assets/images/horizontalCards/Raze2.jpg'),
  },
  {
    id: 13,
    name: 'Breach',
    country: 'Suécia',
    biography:
      'Breach, o homem-biônico sueco, dispara poderosos jatos cinéticos para forçar a abertura de um caminho pelo território inimigo. O dano e a interrupção que ele causa garantem que nenhuma luta seja justa.',
    basicHabilities: ['Estopim', 'Pós-Choque'],
    signatureHability: ['Falha Tectônica'],
    ultimateHability: ['Onda Trovejante'],
    aliases: ['Breachy'],
    race: 'Humano',
    role: 'Iniciador',
    codename: 'Breach',
    gunSkin: 'Ragnarocker Frenzy',
    icon: require('../assets/images/icons/Breach.png'),
    horizontalCard1: require('../assets/images/horizontalCards/Breach.jpg'),
    horizontalCard2: require('../assets/images/horizontalCards/Breach2.jpg'),
  },
  {
    id: 14,
    name: 'Skye',
    country: 'Austrália',
    biography:
      'Mandando um salve direto da Austrália, Skye e sua equipe de feras desbravam territórios hostis. Com seus poderes de cura e suas criações que partem pra cima dos inimigos, qualquer equipe ficará mais forte e mais segura tendo Skye como aliada.',
    basicHabilities: ['Predador Explosivo', 'Reflorescer'],
    signatureHability: ['Luz Desbravadora'],
    ultimateHability: ['Rastreadores'],
    aliases: [],
    race: 'Radiante',
    role: 'Iniciador',
    codename: 'Guide',
    gunSkin: 'Swooping Frenzy',
    icon: require('../assets/images/icons/Skye.png'),
    horizontalCard1: require('../assets/images/horizontalCards/Skye.jpg'),
    horizontalCard2: require('../assets/images/horizontalCards/Skye2.jpg'),
  },
  {
    id: 15,
    name: 'Yoru',
    country: 'Japão',
    biography:
      'Yoru, nativo do Japão, abre fendas na realidade para infiltrar as linhas inimigas sem ser visto. Ele usa tanto artimanhas quanto táticas agressivas, e os alvos são abatidos sem saber de onde o ataque veio.',
    basicHabilities: ['Ponto Cego', 'Falcatrua'],
    signatureHability: ['Passagem Dimensional'],
    ultimateHability: ['Espionagem Dimensional'],
    aliases: [],
    race: 'Radiante',
    role: 'Duelista',
    codename: 'Stealth',
    gunSkin: 'Death Wish Sheriff',
    icon: require('../assets/images/icons/Yoru.png'),
    horizontalCard1: require('../assets/images/horizontalCards/Yoru.png'),
    horizontalCard2: require('../assets/images/horizontalCards/Yoru2.png'),
  },
  {
    id: 16,
    name: 'Astra',
    country: 'Gana',
    biography:
      'Astra, a Agente ganense, utiliza energias cósmicas para moldar o campo de batalha a seu bel-prazer. Com total domínio da sua forma astral e um talento estratégico nato, ela está sempre anos-luz à frente dos inimigos.',
    basicHabilities: ['Pulso Nova', 'Poço Gravitacional'],
    signatureHability: ['Nebulosa'],
    ultimateHability: ['Forma Astral / Divisa Cósmica'],
    aliases: [],
    race: 'Radiante',
    role: 'Controlador',
    codename: 'Rift',
    gunSkin: 'Eclipse Ghost',
    icon: require('../assets/images/icons/Astra.png'),
    horizontalCard1: require('../assets/images/horizontalCards/Astra.png'),
    horizontalCard2: require('../assets/images/horizontalCards/Astra2.png'),
  },
  {
    id: 17,
    name: 'KAY/O',
    country: 'Alternate Timeline Earth',
    biography:
      'KAY/O é uma máquina de guerra construída com um único propósito: neutralizar Radiantes. Ele é capaz de suprimir habilidades inimigas, comprometendo a capacidade de contra-ataque dos adversários e dando a si próprio e a seus aliados uma vantagem essencial em combate.',
    basicHabilities: ['Granada/Clarão', 'Frag/mento'],
    signatureHability: ['Ponto/Zero'],
    ultimateHability: ['Anular/CMD'],
    aliases: [],
    race: 'Robô',
    role: 'Iniciador',
    codename: 'Grenadier',
    gunSkin: 'FIRE-ARM Classic',
    icon: require('../assets/images/icons/KAYO.png'),
    horizontalCard1: require('../assets/images/horizontalCards/KAYO.png'),
    horizontalCard2: require('../assets/images/horizontalCards/KAYO2.png'),
  },
  {
    id: 18,
    name: 'Chamber',
    country: 'França',
    biography:
      'Bem vestido e armado até os dentes, o criador de armas francês Chamber coloca os inimigos para correr com uma precisão mortal. Use e abuse do arsenal personalizado dele para segurar posições e abater inimigos de longe, criando a defesa perfeita para qualquer plano.',
    basicHabilities: ['Caçador de Cabeças', 'Marca Registrada'],
    signatureHability: ['Rendezvous'],
    ultimateHability: ['Tour de Force'],
    aliases: ['Vincent Fabron'],
    race: 'Humano',
    role: 'Sentinela',
    codename: 'Deadeye',
    gunSkin: 'Finesse Classic',
    icon: require('../assets/images/icons/Chamber.png'),
    horizontalCard1: require('../assets/images/horizontalCards/Chamber.png'),
    horizontalCard2: require('../assets/images/horizontalCards/Chamber2.png'),
  },
  {
    id: 19,
    name: 'Neon',
    country: 'Filipinas',
    biography:
      'Neon, nossa Agente filipina, avança em velocidades incríveis, descarregando surtos de radiância bioelétrica tão rapidamente quanto seu corpo consegue gerá-los. Ela corre à frente para pegar os inimigos de surpresa, abatendo-os mais rápido do que um raio.',
    basicHabilities: ['Ricochete Elétrico', 'Via Expressa'],
    signatureHability: ['Equipamento Voltaico'],
    ultimateHability: ['Sobrecarga'],
    aliases: [],
    race: 'Radiante',
    role: 'Duelista',
    codename: 'Sprinter',
    gunSkin: 'Live Wire Frenzy',
    icon: require('../assets/images/icons/Neon.png'),
    horizontalCard1: require('../assets/images/horizontalCards/Neon.png'),
    horizontalCard2: require('../assets/images/horizontalCards/Neon2.png'),
  },
];

export default class Home extends React.Component {
  constructor(props) {
    super(props);
  }

  render() {
    const { navigation } = this.props;

    return (
      <View style={styles.mainView}>
        <CustomHeader
          title="Valorant Agents"
          description="Descubra mais sobre cada agente clicando na lista abaixo"
        />

        <CustomFlatlist data={agents} navigation={navigation} />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  mainView: {
    padding: 20,
    backgroundColor: '#ff4457',
    height: '100%',
  },
});
